name: Run tests
on:
  - push
  - workflow_call
jobs:
  test-suites:
    runs-on: ubuntu-latest
    # Stop the occasional rogue instance before the 6h GitHub limit
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install everything
        run: npm install
      - name: Ng test for studio-web
        run: |
          npx nx build web-component
          npx nx test:once studio-web
      - name: Cypress run for web-component
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: |
            npx nx serve web-component
            npx nx serve-test-data web-component
          wait-on: "http://localhost:3333/build/web-component.esm.js"
          command: npx nx test:once web-component
      - name: Check that i18n and l10n are up to date
        run: |
          npx nx extract-i18n studio-web
          if diff -w <(git show HEAD:packages/studio-web/src/i18n/messages.json | sort) <(sort < packages/studio-web/src/i18n/messages.json); then echo OK: The i18n database is up to date.; else echo ERROR: The i18n database is out of date.; npx nx check-l10n studio-web || echo ERROR: The l10n databases are also out of date.; false; fi
          if npx nx check-l10n studio-web; then echo OK: The l10n databases are up to date.; else echo ERROR: An l10n database is out of date.; false; fi
      - name: make sure the WP plugin zip file is in sync
        run: |
          cd packages/web-component/wordpress-plugin
          unzip -d extract read-along-web-app-loader.zip
          if ! diff --exclude=js -qr read-along-web-app-loader extract/read-along-web-app-loader; then \
            echo The zipped WordPress plugin packages/web-component/wordpress-plugin/read-along-web-app-loader.zip is out of date.; \
            false; \
          fi
